// Entirely synthetic published store row. Never import test fixtures into application code.
export function syntheticStore(overrides: Record<string, unknown> = {}) {
  return {
    id: "00000000-0000-4000-8000-000000000001",
    source_key: "synthetic-store",
    external_network_code: null,
    crm_code: null,
    erp_code: null,
    legacy_store_id: null,
    retail_panel_code: null,
    data_sharing_code: null,
    name: "Magasin synthétique",
    legal_name: null,
    address_line_1: null,
    address_line_2: null,
    department_code: null,
    postal_code: null,
    city: null,
    retailer_code: null,
    retailer_name: null,
    store_format: null,
    region_code: null,
    region_name: null,
    sales_representative_code: null,
    sales_representative_name: null,
    promoter_code: null,
    promoter_name: null,
    secondary_representative_code: null,
    secondary_representative_name: null,
    sales_area_sqm: null,
    classification: null,
    segmentation: null,
    distribution_model: null,
    has_direct_sales_potential: null,
    survey_validity_days: null,
    planned_sales_visits: null,
    sales_visit_minutes: null,
    planned_promoter_visits: null,
    promoter_visit_minutes: null,
    planned_total_visits: null,
    checkout_count: null,
    annual_turnover_2025_millions: null,
    annual_turnover_2024_millions: null,
    annual_turnover_2023_millions: null,
    october_2023_turnover_millions: null,
    is_active: true,
    created_at: "2026-01-01T00:00:00Z",
    updated_at: "2026-01-01T00:00:00Z",
    ...overrides,
  };
}
